# Generated by Django 3.2.4 on 2021-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('residencial', 'residencial'), ('comercial', 'comercial')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_dept', models.IntegerField(verbose_name='Costo del departamento')),
                ('num_dept', models.IntegerField(verbose_name='Número de departamentos')),
                ('num_cuarto', models.IntegerField(verbose_name='Número de Cuartos')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='administrativo.edificio')),
            ],
        ),
    ]
